/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    // Adicione explicitamente os caminhos dos componentes
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/components/*.{js,jsx,ts,tsx}",
    "./src/pages/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    // Classes dinâmicas usadas nos componentes
    'fixed',
    'z-50',
    'z-40',
    'bottom-6',
    'right-6', 
    'left-6',
    'w-12', 'h-12',
    'w-14', 'h-14',
    'w-5', 'h-5',
    'w-6', 'h-6',
    'w-7', 'h-7',
    'w-8', 'h-8',
    'w-10', 'h-10',
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'from-primary',
    'to-secondary',
    'from-green-500',
    'to-green-600',
    'from-green-500/10',
    'to-green-600/10',
    'rounded-full',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'shadow-xl',
    'shadow-2xl',
    'hover:shadow-3xl',
    'text-white',
    'text-white/80',
    'flex',
    'items-center',
    'justify-center',
    'relative',
    'absolute',
    'inset-0',
    'bg-green-500',
    'bg-red-500',
    'bg-gray-900',
    'bg-white',
    'bg-white/20',
    'bg-black/50',
    'bg-primary/5',
    'bg-gray-50',
    'opacity-0',
    'group-hover:opacity-100',
    'transform',
    'translate-y-1/2',
    'rotate-45',
    'whitespace-nowrap',
    'pointer-events-none',
    'mt-3',
    'hover:shadow-2xl',
    'backdrop-blur-sm',
    'border',
    'border-gray-100',
    'border-gray-200',
    'hover:border-primary/30',
    'border-t',
    'border-gray-100',
    'p-3', 'p-4',
    'space-y-3',
    'max-h-96',
    'overflow-y-auto',
    'line-clamp-2',
    'text-center',
    'text-xs', 'text-sm', 'text-lg',
    'font-bold', 'font-semibold',
    'text-gray-800', 'text-gray-500', 'text-gray-600',
    'text-green-600',
    'group-hover:scale-110',
    'hover:bg-white/30',
    'hover:bg-primary/5',
    // Classes de animação
    'group-hover:opacity-100',
    'group-hover:scale-110',
    // Posicionamento
    '-top-1',
    '-right-1',
    'left-16',
    'bottom-24',
    // Transições
    'transition-all',
    'transition-colors',
    'transition-opacity',
    'transition-transform',
    'duration-200',
    'duration-300',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#1a365d',
        secondary: '#d4a017',
        accent: '#2d3748',
        light: '#f8f9fa',
        dark: '#1a202c',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s infinite',
        'fade-in-up': 'fade-in-up 0.8s ease-out',
        'shimmer': 'shimmer 2s infinite linear',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(212, 160, 23, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(212, 160, 23, 0.6)' },
        },
        'fade-in-up': {
          'from': { opacity: '0', transform: 'translateY(30px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
      },
      boxShadow: {
        'soft': '0 10px 40px rgba(0, 0, 0, 0.08)',
        'hard': '0 20px 60px rgba(0, 0, 0, 0.15)',
        'glow': '0 0 40px rgba(212, 160, 23, 0.4)',
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
      }
    },
  },
  plugins: [],
}